DB stuff
TeenGamingNights/AssemblyMod pull request #6
Opened 2018-12-25 13:22 UTC by Dot-Rar

2018-12-25 13:23 UTC, aecsocket approved these changes

2018-12-26 19:49 UTC, NahuLD commented on build.gradle
> +    compile 'org.json:json:+'
Don't do this you goofus, specify the version

2018-12-26 19:50 UTC, NahuLD requested changes
Fix the version meme and I'll approve

2018-12-26 19:51 UTC, NahuLD approved these changes

2018-12-26 20:53 UTC, merged